# NOTE: update this with your service name
service: result-service

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    exams: exams
    questions: questions
    results: results
    userExams: userExams
    saved: saved
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

functions:
  startExam:
    handler: src/startExam.main
    events:
      - http:
          path: attempt/{id}
          method: get
          cors: true
          authorizer: aws_iam
  getQuestions:
    handler: src/getQuestions.main
    events:
      - http:
          path: attemptq/{id}
          method: get
          cors: true
          authorizer: aws_iam
  saveQuestionAnswer:
    handler: src/saveQuestionAnswer.main
    events:
      - http:
          path: attempt/{id}
          method: post
          cors: true
          authorizer: aws_iam
  endExam:
    handler: src/endExam.main
    events:
      - http:
          path: end/{id}
          method: get
          cors: true
          authorizer: aws_iam
  getMyGrade:
    handler: src/getMyGrade.main
    events:
      - http:
          path: grade/{id}
          method: get
          cors: true
          authorizer: aws_iam
  getExamGrade:
    handler: src/getExamGrade.main
    events:
      - http:
          path: mygrade/{id}
          method: get
          cors: true
          authorizer: aws_iam
